apiVersion: v1
kind: ServiceAccount
metadata:
  name: bedrock-authn
  namespace: bedrock-system
  labels:
    bedrock.cloudyfolks.io/component: authn
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bedrock-authn
  labels:
    bedrock.cloudyfolks.io/component: authn
rules:
  - apiGroups: [bedrock.cloudyfolks.io]
    resources:
      - apitokens
      - apitokens/status
      - authcodes
      - authcodes/status
      - authrequests
      - authrequests/status
      - credentials
      - credentials/status
      - devicerequests
      - devicerequests/status
      - groups
      - groups/status
      - identityproviders
      - identityproviders/status
      - oauthclients
      - oauthclients/status
      - refreshtokens
      - refreshtokens/status
      - sessions
      - sessions/status
      - signingkeys
      - signingkeys/status
      - users
      - users/status
    verbs: [create, delete, get, list, patch, update, watch]
  - apiGroups: [bedrock.cloudyfolks.io]
    resources: [settings, clusters]
    verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bedrock-authn
  labels:
    bedrock.cloudyfolks.io/component: authn
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bedrock-authn
subjects:
  - kind: ServiceAccount
    name: bedrock-authn
    namespace: bedrock-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bedrock-authn
  namespace: bedrock-system
  labels:
    bedrock.cloudyfolks.io/component: authn
rules:
  - apiGroups: [""]
    resources: [secrets]
    verbs: [create, get, list, watch, update, patch, delete]
  - apiGroups: [""]
    resources: [configmaps]
    resourceNames: [kube-root-ca.crt]
    verbs: [get]
  - apiGroups: [coordination.k8s.io]
    resources: [leases]
    verbs: [get, list, watch, create, update]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bedrock-authn
  namespace: bedrock-system
  labels:
    bedrock.cloudyfolks.io/component: authn
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bedrock-authn
subjects:
  - kind: ServiceAccount
    name: bedrock-authn
    namespace: bedrock-system
